
import React from 'react';
import DocLayout from '@/components/DocLayout';
import { Play, Clock, ChevronRight } from 'lucide-react';

const DataAnalysis = () => {
  const sidebarLinks = [
    { title: 'All Videos', url: '/documentation/videos' },
    { title: 'Building AI Workflows', url: '/documentation/videos/ai-workflows' },
    { title: 'Advanced Automation', url: '/documentation/videos/advanced-automation' },
    { title: 'Custom Integrations', url: '/documentation/videos/custom-integrations' },
    { title: 'Data Analysis', url: '/documentation/videos/data-analysis', active: true },
  ];

  const videos = [
    {
      id: 'video4',
      title: 'Data Analysis Dashboards',
      description: 'Create powerful data visualizations from your workflow results',
      duration: '10:21',
      thumbnail: 'https://images.unsplash.com/photo-1560807707-8cc77767d783?w=600&h=400&fit=crop',
      level: 'Intermediate'
    },
    {
      id: 'video8',
      title: 'Predictive Analytics with Workflow Data',
      description: 'Use historical workflow data to build predictive models',
      duration: '20:15',
      thumbnail: 'https://images.unsplash.com/photo-1599658880436-c61792e70672?w=600&h=400&fit=crop',
      level: 'Advanced'
    },
    {
      id: 'video15',
      title: 'Real-time Data Monitoring',
      description: 'Set up real-time dashboards and alerts for your workflow data',
      duration: '13:37',
      thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&h=400&fit=crop',
      level: 'Intermediate'
    },
    {
      id: 'video16',
      title: 'Advanced Reporting Techniques',
      description: 'Create custom reports and visualizations for stakeholders',
      duration: '16:24',
      thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&h=400&fit=crop',
      level: 'Advanced'
    }
  ];

  return (
    <DocLayout
      title="Data Analysis Features"
      description="Turn your workflow data into actionable insights"
      sidebarLinks={sidebarLinks}
      breadcrumbs={[
        { title: 'Video Tutorials', url: '/documentation/videos' },
        { title: 'Data Analysis', url: '/documentation/videos/data-analysis' }
      ]}
      previousLink={{ title: 'Custom Integrations', url: '/documentation/videos/custom-integrations' }}
    >
      <section className="mb-8">
        <p className="text-lg mb-6">
          Learn how to harness the power of data generated by your workflows. These tutorials cover data visualization, reporting, predictive analytics, and real-time monitoring techniques.
        </p>
      </section>

      <section className="mb-12">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {videos.map((video) => (
            <div key={video.id} className="border border-gray-200 rounded-lg overflow-hidden">
              <div className="relative">
                <img 
                  src={video.thumbnail}
                  alt={`${video.title} thumbnail`}
                  className="w-full h-auto object-cover aspect-video"
                />
                <div className="absolute inset-0 bg-black bg-opacity-30 flex items-center justify-center opacity-0 hover:opacity-100 transition-opacity">
                  <button className="bg-white bg-opacity-90 rounded-full p-3 hover:bg-opacity-100 transition-colors">
                    <Play className="h-6 w-6 text-indigo-600" />
                  </button>
                </div>
                <div className="absolute bottom-2 right-2 bg-black bg-opacity-70 text-white px-2 py-1 rounded text-xs flex items-center">
                  <Clock className="h-3 w-3 mr-1" />
                  {video.duration}
                </div>
              </div>
              <div className="p-4">
                <div className="flex justify-between items-start mb-2">
                  <h3 className="font-semibold">{video.title}</h3>
                  <span className={`text-xs px-2 py-1 rounded ${
                    video.level === 'Beginner' ? 'bg-green-100 text-green-800' :
                    video.level === 'Intermediate' ? 'bg-blue-100 text-blue-800' :
                    'bg-indigo-100 text-indigo-800'
                  }`}>
                    {video.level}
                  </span>
                </div>
                <p className="text-gray-700 text-sm mb-3 line-clamp-2">
                  {video.description}
                </p>
                <a href="#" className="text-indigo-600 hover:text-indigo-800 text-sm font-medium flex items-center">
                  Watch tutorial
                  <ChevronRight className="h-4 w-4 ml-1" />
                </a>
              </div>
            </div>
          ))}
        </div>
      </section>

      <section className="mb-10">
        <h2 className="text-2xl font-bold mb-4">Data Analysis Resources</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="p-6 bg-gray-50 border border-gray-200 rounded-lg">
            <h3 className="font-semibold text-lg mb-3">Report Templates</h3>
            <p className="text-gray-700 mb-4">
              Download ready-to-use report templates to quickly visualize your workflow data.
            </p>
            <a href="#" className="text-indigo-600 hover:text-indigo-800 font-medium">
              Browse templates
            </a>
          </div>
          <div className="p-6 bg-gray-50 border border-gray-200 rounded-lg">
            <h3 className="font-semibold text-lg mb-3">Data Export Guide</h3>
            <p className="text-gray-700 mb-4">
              Learn how to export your workflow data for use in external analytics tools.
            </p>
            <a href="#" className="text-indigo-600 hover:text-indigo-800 font-medium">
              Read guide
            </a>
          </div>
        </div>
      </section>
    </DocLayout>
  );
};

export default DataAnalysis;
